set_global_assignment -entity "pll_test_25" -library "lib_pll_test_25" -name IP_TOOL_NAME "altera_pll"
set_global_assignment -entity "pll_test_25" -library "lib_pll_test_25" -name IP_TOOL_VERSION "18.0"
set_global_assignment -entity "pll_test_25" -library "lib_pll_test_25" -name IP_TOOL_ENV "mwpim"
set_global_assignment -library "lib_pll_test_25" -name SPD_FILE [file join $::quartus(sip_path) "pll_test_25.spd"]

set_global_assignment -library "lib_pll_test_25" -name MISC_FILE [file join $::quartus(sip_path) "pll_test_25_sim/pll_test_25.vho"]
